default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yara_backend_development
test:
  <<: *default
  database: yara_backend_test
staging:
  <<: *default
  database: yara_backend_staging
  username: yara_backend
  password:

production:
  <<: *default
  database: yara_backend_production
