default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yara_backend_development
test:
  <<: *default
  database: yara_backend_test
staging:
  <<: *default
  database: <%= ENV['STAGING_DATABASE_NAME'] %>
  username: <%= ENV['STAGING_DATABASE_USER_NAME'] %>
  password: <%= ENV['STAGING_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['PROD_DATABASE_NAME'] %>
  username: <%= ENV['PROD_DATABASE_USER_NAME'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>